### ISSUE TITLE
pluginlib not found, debain

### ISSUE THREAD

**Issue by JohnDray** [slynobody/SteamOS-wallpaper-engine-kde-plugin#3]
This happens when i open a scene wallpaper
![help](https://github.com/user-attachments/assets/b8dab01a-eef0-46de-b9c4-7e5e97f13f47)

**Comment by slynobody** [comment]
did you install the *.deb (for kde 5->qt5 or for kde 6>qt6)) or did you install just the plugin (f.e. via appstore / discover)?

maybe you installed the deb of the wrong qt-version.

please give output of:
`plasmashell --version`
`lsb_release -a`

**Comment by JohnDray** [comment]
i installed the plugin through the discover app and tried to install the dependencies.  
plasmashell 5.27.5
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

Thanks for helping me.

**Comment by slynobody** [comment]
no need to install the through discover and/or install dependencies manually on debian, just install the deb:

> wget https://github.com/slynobody/SteamOS-wallpaper-engine-kde-plugin/releases/download/0.5.5/int_wallpaper_engine_1-1_amd64.deb
>
> sudo apt install ./int_wallpaper_engine_1-1_amd64.deb

**Comment by JohnDray** [comment]
Ive attempted to do that, copy paste. Ive uninstalled the plugin before I installed the deb file, still the same result. Plugin installed but apparently plugin lib isn't. 

Thanks again.

**Comment by slynobody** [comment]
did you do a reset afterwards?

if this does not help

did the deb-installation had any errors?
what does that output?
`ls -la /usr/lib/x86_64-linux-gnu/qt5/qml/com/github/catsout/wallpaperEngineKde`

how do you uninstalled the plugin?
what does that output?
`ls -la /.local/share/plasma/wallpapers/com.github.catsout.wallpaperEngineKde`

the qt6 version runs scenes right after installation, even if you have installed the plugin twice, in userland, through discover.

**Comment by JohnDray** [comment]
ls -la /usr/lib/x86_64-linux-gnu/qt5/qml/com/github/catsout/wallpaperEngineKde
total 104504
drwxr-xr-x 2 root root      4096 Sep  4 22:30 .
drwxr-xr-x 3 root root      4096 Sep  4 22:30 ..
-rw-r--r-- 1 root root 106996584 Oct 30  2023 libWallpaperEngineKde.so
-rw-r--r-- 1 root root       151 Oct 30  2023 qmldir

**Comment by JohnDray** [comment]
just did put down the 2 commands. down in my terminal without root. 
1:
drwxr-xr-x 2 root root      4096 Sep  4 22:30 .
drwxr-xr-x 3 root root      4096 Sep  4 22:30 ..
-rw-r--r-- 1 root root 106996584 Oct 30  2023 libWallpaperEngineKde.so
-rw-r--r-- 1 root root       151 Oct 30  2023 qmldir
2:
cannot access '/home/'user'/.local/share/plasma/wallpapers/com.github.catsout.wallpaperEngineKde': No such file or directory

the deb installation did come up with an error the first time i installed it, i accidentally exited the konsole window before i tired it. 
thanks,

**Comment by slynobody** [comment]
man, this deb is to make installation simple, to be a no-brainer.

change wallpaper to something other, then uninstall everything wpe-related
```
sudo apt remove int-wallpaper-engine
plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde
sudo rm -R /usr/lib/x86_64-linux-gnu/qt5/qml/com/github/catsout
```

and then a fresh install again (afterwards reboot)
```
wget https://github.com/slynobody/SteamOS-wallpaper-engine-kde-plugin/releases/download/0.5.5/int_wallpaper_engine_1-1_amd64.deb
sudo apt install ./int_wallpaper_engine_1-1_amd64.deb

```

if that does not work, you could try the following: (to work around a bug in the wpe-code that is not fixed yet)
- identify the directory where the 'asset'-folder resides (f.e. "/SteamLibrary/steamapps/common/wallpaper_engine/assets")
- then
```
rm /steamlibrary/steamapps/common/wallpaper_engine/assets
ln -s <YourAssetFolder> /steamlibrary/steamapps/common/wallpaper_engine
```
