### ISSUE TITLE
plugin lib missing file（Steamos）

### ISSUE THREAD

**Issue by chinalhx** [slynobody/SteamOS-wallpaper-engine-kde-plugin#4]
I have executed the command and
 qtwebsockets 
python3 
qtwebchannel is installed correctly
 but now the last plugin lib (for scene, mpv) is missing And I can’t find wallpaper engine (new) in the discover store. Has it been removed from the shelves?
So,how to solve it?
![image](https://github.com/user-attachments/assets/b7a2ce78-7684-4811-a322-4b1b8e80c0bb)

**Comment by chinalhx** [comment]
@slynobody pls!dude,need some help

**Comment by slynobody** [comment]
what commands have you executed exactly? did you remove your former git-install completely (or did a 'git pull')?

the routine here usually installs the plasma-plugin too, you dont need the discover-store-plugin (whatmay give you version-inconsistencies you seem to have currently).

what happens if you do:
```
`plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`
remove your local former version of the git
reinstall the git 
```

i updated the information in the discover-store, they are looking through it now, it usually takes 1-5 days for them to set it online again, then you can install the plugin only through the store (without the lib).

**Comment by chinalhx** [comment]
> what commands have you executed exactly? did you remove your former git-install completely (or did a 'git pull')?
> 
> the routine here usually installs the plasma-plugin too, you dont need the discover-store-plugin (whatmay give you version-inconsistencies you seem to have currently).
> 
> what happens if you do:
> 
> ```
> `plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`
> remove your local former version of the git
> reinstall the git 
> ```
> 
> i updated the information in the discover-store, they are looking through it now, it usually takes 1-5 days for them to set it online again, then you can install the plugin only through the store (without the lib).

Of course there are those before they are completely deleted! Because I have restored factory settings many times! But it still doesn't work (the plugin lib file is missing) The executed command is git clone written on your homepage, then cd, then chmod+x, then ./install. I followed the code you provided exactly step by step, but in the end the plugin lib was still missing (even the factory settings were restored 2-3 times)

**Comment by chinalhx** [comment]
> what commands have you executed exactly? did you remove your former git-install completely (or did a 'git pull')?
> 
> the routine here usually installs the plasma-plugin too, you dont need the discover-store-plugin (whatmay give you version-inconsistencies you seem to have currently).
> 
> what happens if you do:
> 
> ```
> `plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`
> remove your local former version of the git
> reinstall the git 
> ```
> 
> i updated the information in the discover-store, they are looking through it now, it usually takes 1-5 days for them to set it online again, then you can install the plugin only through the store (without the lib).

In my impression, there was no problem before, but today, as the store removed it, the plugin lib file was missing again. Oh my god.

**Comment by chinalhx** [comment]
I mean is there any other way? Is it possible to install plugin lib through code? Except store version

**Comment by slynobody** [comment]
dont hesitate. it does not get you anywhere. drink a cup of tea and relax. this is not the world. this is a wallpaper-effect for your computer.

1. you dont have to revert to factory settings because of this.
2. the plugin will come back to discover-store (sooner or later). but you *dont* need it anyway if you work from git.
3. cd into to dir where you cloned the git (konsole:

` cd SteamOS-wallpaper-engine-kde-plugin`

6. enter this (as user, not as root)

```
sudo steamos-readonly disable
sudo pacman -R gstreamer-vaapi gst-plugin-pipewire gst-plugins-bad-libs gst-plugins-good gst-plugins-ugly mpv python-websockets qt5-websockets
plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde
qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///media/sda2/Background/SpaceWall/Escape_Function.jpg")}'
sudo rm -r /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde
cd ..
sudo rm -r SteamOS-wallpaper-engine-kde-plugin  
```

7. reinstall from git

**Comment by chinalhx** [comment]
> dont hesitate. it does not get you anywhere. drink a cup of tea and relax. this is not the world. this is a wallpaper-effect for your computer.
> 
> 1. you dont have to revert to factory settings because of this. (never because of things like a kde-plugin, you can simple uninstall it)
> 2. the plugin will come back to discover-store (sooner or later). but you _dont_ need it anyway if you work from git (the store only has the plugin, the git has the plugin+the lib).
> 3. cd into to dir where you cloned the git (konsole:
> 
> ` cd SteamOS-wallpaper-engine-kde-plugin`
> 
> 6. enter this (as user, not as root)
> 
> ```
> sudo steamos-readonly disable
> sudo pacman -R gstreamer-vaapi gst-plugin-pipewire gst-plugins-bad-libs gst-plugins-good gst-plugins-ugly mpv python-websockets qt5-websockets
> plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde
> qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript 'var allDesktops = desktops();print (allDesktops);for (i=0;i<allDesktops.length;i++) {d = allDesktops[i];d.wallpaperPlugin = "org.kde.image";d.currentConfigGroup = Array("Wallpaper", "org.kde.image", "General");d.writeConfig("Image", "file:///media/sda2/Background/SpaceWall/Escape_Function.jpg")}'
> sudo rm -r /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde
> cd ..
> sudo rm -r SteamOS-wallpaper-engine-kde-plugin  
> ```
> 
>  7. dont install any wp-file from discover
> 8. reinstall from git
> 
> i tried it myself on a clean install. it worked without any problems. even scene-files formerly did not work do work now.

So, you mean the store version or the git version, both installation methods, can you choose one of them? Or is it that the store version is simpler? But missing plugin lib? the other hand ,for git version can be simpler?(include plugin lib)?

**Comment by chinalhx** [comment]
I tried it again and it still didn’t work! The plugin lib is missing, it prompts that the plugin__installation is missing? Just after I executed sudo pacman -S to install, an error occurred in rm in the next step, prompting that the plug-in __ installation was missing (and no name was displayed? It was suspected to be a bug)? In addition, the store version is already on the shelves. I also tried it, but it still doesn’t work! Missing plugin lib

**Comment by slynobody** [comment]
yes, you can choose one installation method: chose git or store version. the store version alone does not have the library ('plugin lib is missing', discover cant install libraries).

so if you want scene- and web-support through the library, you just install the git-version - after you removed the discover-version.
if you installed through git before, and something got updated on git, you do a remove first ("./remove.sh")

your error-info is to unspecific.
i do not support you taking some commands out of the script, trying and playing around with them and ... the thing will not install.

if you want to try the git:
1. simply dont install through discover
2. remove everything like i told you above (or use 'remove.sh')
3. do the install-procedure exactly like mentioned in the readme (and nothing else).

i am a bit tired of this, installing through git is easy. it works. i never get into missing library stuff (only if i played around, so dont expect support if you want to do this, else i get the impression of someone trolling around).

**Comment by slynobody** [comment]
thank you for your input.
