### ISSUE TITLE
error：plugin is not installed（steamos）

### ISSUE THREAD

**Issue by chinalhx** [slynobody/SteamOS-wallpaper-engine-kde-plugin#5]
check this log：
(deck@steamdeck ~)$ git clone https://github.com/slynobody/SteamOS-wallpaper-engine-kde-plugin

cd SteamOS-wallpaper-engine-kde-plugin

chmod +x ./install.sh

./install.sh
Cloning into 'SteamOS-wallpaper-engine-kde-plugin'...

remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 211 (delta 45), reused 117 (delta 40), pack-reused 81 (from 1)
Receiving objects: 100% (211/211), 68.95 MiB | 4.58 MiB/s, done.
Resolving deltas: 100% (47/47), done.
>>> copying the wpe-library needs privileges >>> no password set yet? >>> simply enter 'passwd'
Warning: The rootfs is already read-write!
         Nothing is performed.
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/42EC47B816B6D07D7C282A7EA826EC2A7A253879.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 5 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 33 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:  75  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  54  signed:  22  trust: 54-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-11-09
==> Appending keys from holo.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 5 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:  10  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  10  signed:  77  trust: 0-, 0q, 0n, 10m, 0f, 0u
gpg: depth: 2  valid:  55  signed:  22  trust: 55-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2024-11-09
:: Synchronizing package databases...
 jupiter-3.5 is up to date
 holo-3.5 is up to date
 core-3.5 is up to date
 extra-3.5 is up to date
 community-3.5 is up to date
 multilib-3.5 is up to date
:: Starting full system upgrade...
 there is nothing to do
resolving dependencies...
looking for conflicting packages...

Packages (39) a52dec-0.8.0-2  aalib-1.4rc5-16  fftw-3.3.10-4  glslang-12.1.0-2  gssdp-1.6.2-1
              gupnp-1:1.6.3-1  gupnp-igd-1.6.0-1  hwloc-2.9.1-1  imlib2-1.11.1-1  libcaca-0.99.beta20-2
              libcdio-2.1.0-3  libcdio-paranoia-10.2+2.0.1-3  libdv-1.0.0-11  libdvdnav-6.1.1-2
              libdvdread-6.1.3-2  libmpeg2-0.5.1-8  libnice-0.1.21-2  libplacebo-5.229.2-2
              libshout-1:2.4.6-2  libxpresent-1.0.1-1  luajit-2.1.0.beta3.r481.g51fb2f2c-1  mujs-1.3.3-1
              openmpi-4.1.5-2  openpmix-4.2.3-2  rubberband-3.2.1-1  shaderc-2023.3-1  spirv-tools-2022.4-1
              twolame-0.4.0-3  uchardet-0.0.8-1  wavpack-5.6.0-1  wayland-protocols-1.32-1
              gst-plugin-pipewire-1:0.3.62-1.2  gst-plugins-bad-libs-1.22.3-6  gst-plugins-good-1.22.3-6
              gst-plugins-ugly-1.22.3-6  gstreamer-vaapi-1.22.3-6  mpv-1:0.35.1-6  python-websockets-10.4-3
              qt5-websockets-5.15.9+kde+r2-1

Total Download Size:    26.03 MiB
Total Installed Size:  101.60 MiB

:: Proceed with installation? [Y/n] y
warning: no /var/cache/pacman/pkg/ cache exists, creating...
:: Retrieving packages...
 imlib2-1.11.1-1-x86_64                568.3 KiB   397 KiB/s 00:01 [####################################] 100%
 openpmix-4.2.3-2-x86_64               837.5 KiB   569 KiB/s 00:01 [####################################] 100%
 spirv-tools-2022.4-1-x86_64          1448.5 KiB   905 KiB/s 00:02 [####################################] 100%
 fftw-3.3.10-4-x86_64                    2.8 MiB  1351 KiB/s 00:02 [####################################] 100%
 python-websockets-10.4-3-x86_64         3.2 MiB  1561 KiB/s 00:02 [####################################] 100%
 glslang-12.1.0-2-x86_64                 3.1 MiB  1485 KiB/s 00:02 [####################################] 100%
 gst-plugins-good-1.22.3-6-x86_64        2.2 MiB  1056 KiB/s 00:02 [####################################] 100%
 gst-plugins-bad-libs-1.22.3-6-x86_64    2.4 MiB  1159 KiB/s 00:02 [####################################] 100%
 mpv-1:0.35.1-6-x86_64                1676.8 KiB   790 KiB/s 00:02 [####################################] 100%
 wavpack-5.6.0-1-x86_64                494.6 KiB  1401 KiB/s 00:00 [####################################] 100%
 openmpi-4.1.5-2-x86_64                  2.9 MiB  1289 KiB/s 00:02 [####################################] 100%
 hwloc-2.9.1-1-x86_64                  531.4 KiB  1098 KiB/s 00:00 [####################################] 100%
 libnice-0.1.21-2-x86_64               313.9 KiB  1256 KiB/s 00:00 [####################################] 100%
 libcaca-0.99.beta20-2-x86_64          420.6 KiB  1087 KiB/s 00:00 [####################################] 100%
 libplacebo-5.229.2-2-x86_64           392.7 KiB  1015 KiB/s 00:00 [####################################] 100%
 mujs-1.3.3-1-x86_64                   292.6 KiB   813 KiB/s 00:00 [####################################] 100%
 luajit-2.1.0.beta3.r481.g51fb2f2...   321.4 KiB   606 KiB/s 00:01 [####################################] 100%
 gst-plugins-ugly-1.22.3-6-x86_64      211.5 KiB   592 KiB/s 00:00 [####################################] 100%
 libcdio-2.1.0-3-x86_64                255.4 KiB   698 KiB/s 00:00 [####################################] 100%
 rubberband-3.2.1-1-x86_64             260.8 KiB   607 KiB/s 00:00 [####################################] 100%
 shaderc-2023.3-1-x86_64               154.1 KiB   402 KiB/s 00:00 [####################################] 100%
 gstreamer-vaapi-1.22.3-6-x86_64       317.7 KiB   409 KiB/s 00:01 [####################################] 100%
 aalib-1.4rc5-16-x86_64                136.6 KiB   451 KiB/s 00:00 [####################################] 100%
 gupnp-1:1.6.3-1-x86_64                123.9 KiB   344 KiB/s 00:00 [####################################] 100%
 wayland-protocols-1.32-1-any          103.0 KiB   387 KiB/s 00:00 [####################################] 100%
 libdvdread-6.1.3-2-x86_64             104.2 KiB   279 KiB/s 00:00 [####################################] 100%
 twolame-0.4.0-3-x86_64                 84.3 KiB   253 KiB/s 00:00 [####################################] 100%
 libmpeg2-0.5.1-8-x86_64                81.4 KiB   239 KiB/s 00:00 [####################################] 100%
 uchardet-0.0.8-1-x86_64                80.4 KiB   234 KiB/s 00:00 [####################################] 100%
 qt5-websockets-5.15.9+kde+r2-1-x...    80.3 KiB   234 KiB/s 00:00 [####################################] 100%
 libdv-1.0.0-11-x86_64                  76.9 KiB   185 KiB/s 00:00 [####################################] 100%
 libshout-1:2.4.6-2-x86_64              69.3 KiB   215 KiB/s 00:00 [####################################] 100%
 libcdio-paranoia-10.2+2.0.1-3-x86_64   65.6 KiB   177 KiB/s 00:00 [####################################] 100%
 gssdp-1.6.2-1-x86_64                   59.4 KiB   156 KiB/s 00:00 [####################################] 100%
 libdvdnav-6.1.1-2-x86_64               56.1 KiB   172 KiB/s 00:00 [####################################] 100%
 gst-plugin-pipewire-1:0.3.62-1.2...    54.5 KiB   158 KiB/s 00:00 [####################################] 100%
 a52dec-0.8.0-2-x86_64                  46.3 KiB   148 KiB/s 00:00 [####################################] 100%
 gupnp-igd-1.6.0-1-x86_64               28.8 KiB  92.9 KiB/s 00:00 [####################################] 100%
 libxpresent-1.0.1-1-x86_64             18.0 KiB  47.4 KiB/s 00:00 [####################################] 100%
 Total (39/39)                          26.0 MiB  5.71 MiB/s 00:05 [####################################] 100%
(39/39) checking keys in keyring                                   [####################################] 100%
(39/39) checking package integrity                                 [####################################] 100%
(39/39) loading package files                                      [####################################] 100%
(39/39) checking for file conflicts                                [####################################] 100%
(39/39) checking available disk space                              [####################################] 100%
:: Processing package changes...
( 1/39) installing gssdp                                           [####################################] 100%
Optional dependencies for gssdp
    gtk4: gssdp-device-sniffer
( 2/39) installing gupnp                                           [####################################] 100%
Optional dependencies for gupnp
    python: gupnp-binding-tool [installed]
( 3/39) installing gupnp-igd                                       [####################################] 100%
( 4/39) installing libnice                                         [####################################] 100%
Optional dependencies for libnice
    gstreamer: "nice" GStreamer plugin [installed]
( 5/39) installing wayland-protocols                               [####################################] 100%
( 6/39) installing gst-plugins-bad-libs                            [####################################] 100%
( 7/39) installing gstreamer-vaapi                                 [####################################] 100%
( 8/39) installing gst-plugin-pipewire                             [####################################] 100%
( 9/39) installing wavpack                                         [####################################] 100%
(10/39) installing aalib                                           [####################################] 100%
Optional dependencies for aalib
    xorg-fonts-misc: x11 driver
    xorg-mkfontscale: x11 driver
(11/39) installing libdv                                           [####################################] 100%
(12/39) installing libshout                                        [####################################] 100%
(13/39) installing imlib2                                          [####################################] 100%
Optional dependencies for imlib2
    libheif: HEIF loader (for AVIF)
    libid3tag: ID3 loader
    libjxl: JXL loader [installed]
    librsvg: SVG loader [installed]
    libspectre: PS loader [installed]
    libwebp: WEBP loader [installed]
    openjpeg2: J2K loader [installed]
(14/39) installing libcaca                                         [####################################] 100%
Optional dependencies for libcaca
    python: Python bindings [installed]
(15/39) installing twolame                                         [####################################] 100%
(16/39) installing gst-plugins-good                                [####################################] 100%
(17/39) installing libdvdread                                      [####################################] 100%
Optional dependencies for libdvdread
    libdvdcss: Decoding encrypted DVDs
(18/39) installing libmpeg2                                        [####################################] 100%
Optional dependencies for libmpeg2
    libxv: mpeg2dec command [installed]
    sdl: mpeg2dec command
(19/39) installing a52dec                                          [####################################] 100%
(20/39) installing libcdio                                         [####################################] 100%
(21/39) installing gst-plugins-ugly                                [####################################] 100%
(22/39) installing libcdio-paranoia                                [####################################] 100%
(23/39) installing libdvdnav                                       [####################################] 100%
(24/39) installing glslang                                         [####################################] 100%
(25/39) installing spirv-tools                                     [####################################] 100%
(26/39) installing shaderc                                         [####################################] 100%
(27/39) installing libplacebo                                      [####################################] 100%
(28/39) installing libxpresent                                     [####################################] 100%
(29/39) installing luajit                                          [####################################] 100%
(30/39) installing mujs                                            [####################################] 100%
(31/39) installing hwloc                                           [####################################] 100%
Optional dependencies for hwloc
    cairo [installed]
    libxml2 [installed]
    pciutils [installed]
    libx11 [installed]
(32/39) installing openpmix                                        [####################################] 100%
Optional dependencies for openpmix
    openpmix-docs: for documentation
(33/39) installing openmpi                                         [####################################] 100%
Optional dependencies for openmpi
    cuda: cuda support
    gcc-fortran: fortran support
    perl: for aggregate_profile.pl and profile2mat.pl [installed]
(34/39) installing fftw                                            [####################################] 100%
(35/39) installing rubberband                                      [####################################] 100%
(36/39) installing uchardet                                        [####################################] 100%
(37/39) installing mpv                                             [####################################] 100%
Optional dependencies for mpv
    yt-dlp: for video-sharing websites playback
    youtube-dl: for video-sharing websites playback
(38/39) installing python-websockets                               [####################################] 100%
(39/39) installing qt5-websockets                                  [####################################] 100%
Optional dependencies for qt5-websockets
    qt5-declarative: QML bindings [installed]
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating icon theme caches...
(3/3) Updating the desktop file MIME type cache...
Error: Plugin  is not installed.

libWallpaperEngineKde.so
i was copy ur command on github,paste on konsole,still can’t install for plugin lib
![image](https://github.com/user-attachments/assets/61100c4e-9eb3-4f54-a0b0-dd10fb7fa70c)
@slynobody

**Comment by slynobody** [comment]
this error just indicates that you did not have installed the wallpaper-plugin through discover: it tries to remove it if you have installed it before, and does not find it: so for plasma the plugin that should be removed "is not installed".
