### ISSUE TITLE
Plugin lib not found even tho I think I have it

### ISSUE THREAD

**Issue by claymorwan** [slynobody/SteamOS-wallpaper-engine-kde-plugin#6]
When I select a wallpaper I get this error
![image](https://github.com/user-attachments/assets/b8008c13-79df-4183-a001-4e66277c2ea5)
I'm not really sure what is the plugin lib, so I tried to install the `libWallpaperEngineKde.tar.gz` package in this repo but I get this error
```
$ sudo pacman -U libWallpaperEngineKde.tar.gz
[sudo] password for claymorwan: 
loading packages...
error: missing package metadata in libWallpaperEngineKde.tar.gz
error: 'libWallpaperEngineKde.tar.gz': invalid or corrupted package
```
So I checked in the `/usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/` dir and I apparently have something with the same name
```
$ ls
libWallpaperEngineKde.so  qmldir
```
I installed the plugin throught the kde store and needed for arch and arch-based distros
I also can't uninstall the plugin, it just returns this error 
```
Installation of /tmp/HdkrhO-com.github.catsout.wallpaperEngineKde.tar.gz failed: /tmp/HdkrhO-com.github.catsout.wallpaperEngineKde.tar.gz/ does not exist
``` 
I also don't seem to have the side menu shown in the repo's README, maybe I need the plugin lib to have ?

**Comment by slynobody** [comment]
you simply cant install libWallpaperEngineKde.tar.gzr through pacman.
use (or take a look at) install.sh (the tar gets extracted and moved into the right place).

how do you get  libWallpaperEngineKde.so  and qmldir installed /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde/?
did you try to compile it yourself? even on a sd? you would be a hero if you got the compilation working there. thats the point why i offered this installer.

you have to remove everthing already installed before installing this git on a sd. but i suppose you are not on a steamdeck?

**Comment by claymorwan** [comment]
Well I did try the installer, but the plugin still wasn't detected after, which is why I tried pacman
And I honestly have no idea how I got /usr/lib/qt/qml/com/github/catsout/wallpaperEngineKde, maybe with the installer (?) but even with it being there it didn't work
I tried another [fork](https://github.com/fxzjshm/wallpaper-engine-kde-plugin/tree/qt6) which kinda solves, it's kind off a mess cuz I was in a rush and cuz I also couldn't uninstall yours for some reason, I'll try to clean all these when I get home, or try on my main machine which I haven't tried on yet
Btw u said u have a pacman package? Idk if it's for the plugin lib or the whole thing but I'll take it

**Comment by slynobody** [comment]
a) the installer is for sd only
b) after installation you need a reboot (on steamdecks) 
c) you simply cant mix different forks (the version of the lib and the version of the plugin need to be the same or the lib is not loaded at all). 
d) you have to remove everything installed form a specific fork and/or version before trying to install it again

**Comment by claymorwan** [comment]
I'll uninstall everything when I get home, for the fork they have instructions on how to uninstall so it shouldn't be hard, for yours since I installed it through the kde store idk if the uninstall script will work but I'll try
Btw I gotta mention that I installed the fork after checking if the lib was in the directory I mentioned, in case I wasn't clear with it
For installing I think I should use the pacman package, but I suppose I just gotta clone the repo and run the install script right

**Comment by slynobody** [comment]
kde store offers a 'uninstall'-button or do `plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`.

you seemingly compiled on your own what would be the best practice. compilation would be done by cloning the main-repo and following compile-procedures for your distro.

you will *not* need any installer, kde-store-package or pacman-package for this. simply uninstall everything and compile it yourself (which you seemingly already did with the fork).

**Comment by claymorwan** [comment]
> kde store offers a 'uninstall'-button or do `plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde`.
> 
If you're talking about that button for ur plugin, it doesn't work for some reason, I'll try the cmd
So ye if I understood everything correctly I just gotta clean up everything and run the install script and I'm all gud, I'll try that as soon as I get home

**Comment by claymorwan** [comment]
Welp cleaned up everything, rebooted, ran the install script and rebooted again but it doesn't install the plugin itself so ye

**Comment by slynobody** [comment]
845261

**Comment by claymorwan** [comment]
```
$ plasmashell --version 
plasmashell 6.1.5
```
```
$ lsb_release -a 
LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling
```
I suppose it doesn't work cuz of the `steamos-readonly` cmd

**Comment by slynobody** [comment]
no, you have plasma 6 / qt 6, as i mentioned before, this is for plasma 5 (because the steamdeck is on plasma 5 currently). Maybe i provide a plasma 6 pacman-package, but i cannot test it.

**Comment by claymorwan** [comment]
o dam, I thought this was for plasma 6 cuz when searching for wallpaper engine plugin for kde 6 on the kde store, your plugin was the only one available.

**Comment by slynobody** [comment]
though i dont have an arch-based distro at hand currently with qt6, i tried to build a package.

could you try:
```
wget https://github.com/slynobody/SteamOS-wallpaper-engine-kde-plugin/releases/download/0.5.5_qt6_arch/WallpaperEngine_kde_qt6-1_1-1-x86_64.tar.gz
plasmapkg2 -r ~/.local/share/plasma/wallpapers/com.github.casout.wallpaperEngineKde
sudo pacman -U ./WallpaperEngine_kde_qt6-1_1-1-x86_64.pkg.tar.zstz
```

**Comment by slynobody** [comment]
i tried to upload a plasma6-version hopefully installable via pacman -U, does it work?

**Comment by claymorwan** [comment]
This one seems to be working just fine, thanks a lot, and truly sorry for the bother :3
